### ISSUE TITLE
YAML file less content when creating new CR in 4.9

### ISSUE THREAD

**Issue by quchangl-github** [openshift/console#10403]
This issue only happened in OCP 4.9, it's fine in 4.8 and earlier version.

recreate steps:
1. Go to OCP console -> Installed Operator -> RHACM
2. Create one new MCO CR, the YAML view is opened, the YAML contents basic values
```
kind: MultiClusterObservability
apiVersion: observability.open-cluster-management.io/v1beta2
metadata:
  name: observability
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
```
![image](https://user-images.githubusercontent.com/59680818/140679705-ed28fd20-3709-4081-b056-5d956d0b2393.png)

4. move to Form view, and back to YAML view
There are move values in the YAML file
```
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: gp2
    storeStorageSize: 10Gi
```
![image](https://user-images.githubusercontent.com/59680818/140679721-d14a7dfa-c5b0-43ff-aa89-3e5618cacc1c.png)
