### ISSUE TITLE
PodInitializing is not generally an error state, messaging is confusing

### ISSUE THREAD

**Issue by smarterclayton** [openshift/console#107]
![screenshot](https://www.dropbox.com/s/3rr6asgeobdnvwe/Screenshot%202018-06-08%2000.12.18.png?raw=1)

In this case the pod has failed 

```
status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2018-06-08T02:35:19Z'
      reason: ContainersNotInitialized
      message: 'containers with incomplete status: [initupload place-tools]'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2018-06-08T02:35:19Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [test sidecar]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2018-06-08T02:35:19Z'
  hostIP: 10.142.0.6
  podIP: 172.16.14.101
  startTime: '2018-06-08T02:35:19Z'
  initContainerStatuses:
    - name: clonerefs
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2018-06-08T02:35:21Z'
          finishedAt: '2018-06-08T02:35:25Z'
          containerID: >-
            docker://69859fd7510e3a6bd5e8d2b619c31847ac1acd7f2dafeb5eb9b777ef4206bb50
      lastState: {}
      ready: true
      restartCount: 0
      image: 'registry.svc.ci.openshift.org/ci/clonerefs:latest-json'
      imageID: >-
        docker-pullable://registry.svc.ci.openshift.org/ci/clonerefs@sha256:27418befcbf1561f32d97eb47c94d8ffebb4747c19cb8e9ab43f8d594165e0f3
      containerID: >-
        docker://69859fd7510e3a6bd5e8d2b619c31847ac1acd7f2dafeb5eb9b777ef4206bb50
    - name: initupload
      state:
        terminated:
          exitCode: 1
          reason: Error
          startedAt: '2018-06-08T02:35:26Z'
          finishedAt: '2018-06-08T02:35:27Z'
          containerID: >-
            docker://ab37a33572b4fd62793ac3e983e6b560ab9656c4e31287447d2ac7b18fcdbf5d
      lastState: {}
      ready: false
      restartCount: 0
      image: 'registry.svc.ci.openshift.org/ci/initupload:latest-json'
      imageID: >-
        docker-pullable://registry.svc.ci.openshift.org/ci/initupload@sha256:c249cc0438dbd12923b1b2190968f6c3fcb8a06dcfb2060b52ade27924863f21
      containerID: >-
        docker://ab37a33572b4fd62793ac3e983e6b560ab9656c4e31287447d2ac7b18fcdbf5d
    - name: place-tools
      state:
        waiting:
          reason: PodInitializing
      lastState: {}
      ready: false
      restartCount: 0
      image: 'registry.svc.ci.openshift.org/ci/entrypoint:latest-json'
      imageID: ''
  containerStatuses:
    - name: sidecar
      state:
        waiting:
          reason: PodInitializing
      lastState: {}
      ready: false
      restartCount: 0
      image: 'registry.svc.ci.openshift.org/ci/sidecar:latest-json'
      imageID: ''
    - name: test
      state:
        waiting:
          reason: PodInitializing
      lastState: {}
      ready: false
      restartCount: 0
      image: >-
        docker-registry.default.svc:5000/ci/ci-operator@sha256:a3ba73101306cf64bb84f0d2270fd3f31186a97c56bc568bcda52f185eaf645a
      imageID: ''
  qosClass: BestEffort
```

But showing `PodInitializing` here is a bit confusing since it's usually a forward action (the pod is initializing).  I think "InitContainerFailed" or "InitializationFailed" would be more appropriate.
