### ISSUE TITLE
Defaults for creating PersistentVolume don't/won't work

### ISSUE THREAD

**Issue by jsilberm** [openshift/console#11101]
Current default yaml:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /tmp
    server: 172.17.0.2
```

Will not work by default and results in errors, such as ---
```
MountVolume.SetUp failed for volume "vmrh83root" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t nfs 172.17.0.2:/tmp /var/lib/kubelet/pods/745bbef2-2063-40b6-85e8-ddfcc76af855/volumes/kubernetes.io~nfs/vmrh83root Output: mount.nfs: Connection timed out
```
