### ISSUE TITLE
Some pods may not have volumes

### ISSUE THREAD

**Issue by vrutkovs** [openshift/console#1218]
Create a pod which doesn't have volumes and doesn't mount SA token:
```
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: hello-openshift
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080

```
Pod now cannot be viewed:
```
TypeError
Description:

e.spec.volumes is undefined
Component Trace:

in T
    in div
    in I
    in e
    in e
    in div
    in N
    in StatusBox
    in div
    in div
    in t
    in div
    in Unknown
    in Connect(Component)
    in t
    in Connect(t)
    in Unknown
    in div
    in t
    in DetailsPage
    in PodsDetailsPage
    in t
    in Unknown
    in ResourceDetailsPage
    in e
    in e
    in div
    in div
    in section
    in h
    in main
    in div
    in p
    in t
    in e
    in e
    in o
```
