### ISSUE TITLE
missing olm descriptor for multiline strings

### ISSUE THREAD

**Issue by frzifus** [openshift/console#12443]
Is there a way to display multiline strings in the openshift console? Seems there is nothing like this it in the [olm-descriptor-reference](https://github.com/openshift/console/blob/c30f30442e83d788d74714c3871c78398e822917/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#olm-descriptor-reference).

## Scenario

The OpenTelemetry operator gets its [configuration from a string](https://github.com/open-telemetry/opentelemetry-operator/blob/037b673b51a995452ee7883f8975a217cca0afeb/apis/v1alpha1/opentelemetrycollector_types.go#L129) field. A configuration looks like this:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  image: 'ghcr.io/frzifus/otelcontribcol:0.70.0-pre-1'
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols: 
          grpc:
          http:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]

```

In the yaml view the configuration is well readable. This changes in the console form view.

![grafik](https://user-images.githubusercontent.com/10403402/213140421-a4362ff6-26a1-4c51-915b-30ca91c83713.png)
