### ISSUE TITLE
Unable to expose the console through ingress

### ISSUE THREAD

**Issue by atefhares** [openshift/console#13336]
I have deployed the console image  quay.io/openshift/origin-console:4.10 on kubernetes cluster (non-openshift cluster)

But when I access the console from ingress url I get blank page with 404 errors for webpage files
However, it's working fine if service is set to be NodePort

and I'm unable to detect the issue because I am unable to enable logs for the pridge
tried to set the following but still don't see any logs expect that server started.

```
name: BRIDGE_LOG_LEVEL
value: server=1
```

The issue seems to be mostly with how to configure the console to work with URL like 
and the ingress to be configured correctly

```
DOMAIN/dashboard/WHATEVER-CONSOLE-FILE-OR-PAGE
```

but without logs or any evidence if issue is from ingress or from console itself, I'm stuck!

Any advice would be really appreciated 

---
This how I deploy it in summary:
 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.0.3
    helm.sh/chart: openshift-console-0.0.3
  name: REMOVED-openshift-console
  namespace: REMOVED
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openshift-console
    spec:
      containers:
      - env:
        - name: BRIDGE_USER_AUTH
          value: disabled
        - name: BRIDGE_K8S_MODE
          value: off-cluster
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: https://kubernetes.default
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true"
        - name: BRIDGE_K8S_AUTH
          value: bearer-token
        - name: BRIDGE_BASE_ADDRESS
          value: https://DOMAIN/dashboard/
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: openshift-console-sa-token
        image: quay.io/openshift/origin-console:4.10
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: openshift-console
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 2001
          runAsUser: 1001
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: openshift-console-sa
      serviceAccountName: openshift-console-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - emptyDir: {}
        name: tmp-volume
 
```
 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.0.3
    helm.sh/chart: openshift-console-0.0.3
  name: REMOVED-openshift-console
  namespace: REMOVED
spec:
  clusterIP: REMOVED
  clusterIPs:
  - REMOVED
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/name: openshift-console
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
 
``` 
 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: REMOVED-openshift-console
    meta.helm.sh/release-namespace: REMOVED
    nginx.ingress.kubernetes.io/configuration-snippet: "rewrite ^\\/(dashboard)$
      $1/ permanent; \n"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.0.3
    helm.sh/chart: openshift-console-0.0.3
  name: REMOVED-openshift-console
  namespace: REMOVED
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: REMOVED-openshift-console
            port:
              number: 80
        path: /dashboard(/|$)(.*)
        pathType: ImplementationSpecific
```
