### ISSUE TITLE
Native Kubernetes Deployment: namespaces "default" is forbidden

### ISSUE THREAD

**Issue by ryanelian** [openshift/console#1377]
I'm attempting to run OpenShift Console in native Kubernetes (kubeadm) cluster using the instruction from README.

Unlike the README, I'm attempting to run the web console as a pod using this deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konsole-deployment
  namespace: kube-system
  labels:
    app: konsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konsole
  template:
    metadata:
      labels:
        app: konsole
    spec:
      containers:
      - name: konsole-app
        image: quay.io/openshift/origin-console:v4.0.0
        env:
        - name: BRIDGE_K8S_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: myclusteradmin-token-123456
              key: token

---

kind: Service
apiVersion: v1
metadata:
  name: konsole-service
  namespace: kube-system
spec:
  selector:
    app: konsole
  ports:
  - name: http
    port: 80
    targetPort: 9000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: konsole-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/secure-backends: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - konsole.mysite.com
    secretName: konsole-tls
  rules:
  - host: konsole.mysite.com
    http:
      paths:
      - backend:
          serviceName: konsole-service
          servicePort: 80
```

Unfortunately I get this error upon loading the page:

> namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"

![image](https://user-images.githubusercontent.com/8892187/55493656-90a51600-5663-11e9-877f-8c90131c14cd.png)

And the console pod logs:

```
 2019/04/3 15:30:28 cmd/main: cookies are not secure because base-address is not https!
2019/04/3 15:30:28 cmd/main: running with AUTHENTICATION DISABLED!
2019/04/3 15:30:28 cmd/main: Binding to 0.0.0.0:9000...
2019/04/3 15:30:28 cmd/main: not using TLS 
2019/04/3 15:52:29 Failed to dial backend: 'websocket: bad handshake' Status: '403 Forbidden' URL: 'https://10.XX.0.1:443/api/v1/namespaces?watch=true&fieldSelector=metadata.name%3Ddefault'
```

As seen on above YAML, I already set `BRIDGE_K8S_BEARER_TOKEN` environment variable for the pod with token of a ServiceAccount with role: `cluster-admin`. Please help.

Also, how to enable authentication and enable end-to-end TLS?

Thank you in advance.

EDIT: Unrelated question, can OpenShift Console do "kubectl apply"? (**not create**)

**Comment by spadgett** [comment]
I haven't run against native k8s, but this does look like an RBAC issue. Try `kubectl auth can-i` to check if you have correct authorities on the service account.

It should be possible to set up authentication through dex:

https://github.com/dexidp/dex

Console has these flags:

```
  -dex-api-host string
        Target host and port of the Dex API service.
  -dex-client-ca-file string
        PEM File containing trusted CAs for Dex client configuration. If blank, defaults to value of ca-file argument
  -dex-client-cert-file string
        PEM File containing certificates of dex client.
  -dex-client-key-file string
        PEM File containing certificate key of the dex client.
```

`kubectl apply` is not currently possible through console unfortunately.

cc @alecmerdler

**Comment by cmoulliard** [comment]
We suffer from the same issue if we use the instruction of the README

```
[root@cloud console]# export KUBECONFIG=$HOME/.kube/config
[root@cloud console]# source ./contrib/environment.sh
Using https://192.168.99.50:6443
[root@cloud console]# ./bin/bridge
2019/04/16 09:19:27 cmd/main: cookies are not secure because base-address is not https!
2019/04/16 09:19:27 cmd/main: running with AUTHENTICATION DISABLED!
2019/04/16 09:19:27 cmd/main: Binding to 0.0.0.0:9000...
2019/04/16 09:19:27 cmd/main: not using TLS
2019/04/16 09:19:54 Failed to dial backend: 'websocket: bad handshake' Status: '403 Forbidden' URL: 'https://192.168.99.50:6443/api/v1/namespaces?watch=true&fieldSelector=metadata.name%3Ddefault'
```

UI reports : `namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"`

Questions : 

- What is the workaround as we start locally the proxy using the command `./bin/bridge` ? 
- Can we resolve it if we create a `ClusterRoleBinding` ? 
- If no, do we have then to use `OIDC` ?

**Comment by ryanelian** [comment]
> `kubectl apply` is not currently possible through console unfortunately.

😢

**Comment by hellfosa** [comment]
Hello, "BRIDGE_K8S_BEARER_TOKEN" it's wrong env, try to use "BRIDGE_K8S_AUTH_BEARER_TOKEN". 

Fully working config:
```
       - name: BRIDGE_USER_AUTH
          value: disabled
        - name: BRIDGE_K8S_MODE
          value: off-cluster
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: endpoint_of_your_k8s_cluster (https://ip:6443 for example)
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true"
        - name: BRIDGE_K8S_AUTH
          value: bearer-token
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: your_token_name
              key: token

```

**Comment by wilmardo** [comment]
A quick workaround for this is to create a clusterRoleBinding with cluster-admin privileges for the service account referenced as token:
```
kubectl create clusterrolebinding varMyClusterRoleBinding \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:default
```

WARNING: This gives the service account full cluster-admin privileges!

**Comment by alosadagrande** [comment]
Woraround worked fine. 

I also tried to create a new serviceAccount, assign cluster-admin privileges to it and config deployment object of the console to run with that serviceAccount, but same error is shown. 

Should be hardcoded in some part of the console code?

Regards,

**Comment by alosadagrande** [comment]
Hi all,

I created a [blog post and several videos](https://kubevirt.io/2020/OKD-web-console-install.html) about how to run the OpenShift web console on native Kubernetes. It is also explained the serviceaccount issue. 

Hope it helps.

**Comment by ryanelian** [comment]
Back to this thread.

Thank you to everyone who guided me for successfully deploying OKD Console to Native Kubernetes cluster.

(Known good configuration for kubeadm 1.17.4)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-console
  namespace: kube-system
  labels:
    app: origin-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: origin-console
  template:
    metadata:
      labels:
        app: origin-console
    spec:
      containers:
        - name: origin-console-container
          image: quay.io/openshift/origin-console:4.6.0
          env:
            - name: BRIDGE_USER_AUTH
              value: disabled
            - name: BRIDGE_K8S_MODE
              value: off-cluster
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
              value: https://kubernetes.default
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
              value: "true"
            - name: BRIDGE_K8S_AUTH
              value: bearer-token
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: admin-sa-token-abcdef123456 # CHANGE TO YOUR CLUSTER SECRET
                  key: token

---

kind: Service
apiVersion: v1
metadata:
  name: origin-console-svc
  namespace: kube-system
spec:
  selector:
    app: origin-console
  ports:
  - name: http
    port: 80
    targetPort: 9000
```
