### ISSUE TITLE
React error 31 when rendering a CSV specDescriptor with nested objects

### ISSUE THREAD

**Issue by kaczyns** [openshift/console#1685]
We're using OpenShift v4.1.  We're adding spec descriptors to our operator and we've noticed that when the console tries to display instances of our CRD, if it tries to display something that is nested, we get a React error 31 similar to the following:
```
Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ba%2C%20b%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Consider the sample `memcached` operator, described here:
https://github.com/operator-framework/getting-started

We've built it, adding one extra spec field called `newfield`, and pushed it to dockerhub.  I've built a manifest/registry around it which can be installed using this catalogsource:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: memcached-manifests
  namespace: openshift-operator-lifecycle-manager
spec:
  sourceType: grpc
  image: kaczyns/memcached-registry:latest
  displayName: "Memcached Manifest"
```

After deploying the catalogsource and a subscription, edit the CSV YAML to add a second specDescriptor for the `newfield` field:
```yaml
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
          - description: The new field
            displayName: Newfield
            path: newfield
```

Now on an instance of the CRD, add the `newfield` field:
```yaml
spec:
  newfield: fred
  size: 1
```

In the console, navigating to display the CRD instance shows the `Size` of 1, and `Newfield` as fred, since we have a specDescriptor for both.  If I now change newfield:
```yaml
spec:
  newfield:
    first: fred
    last:
      a: example-565cffdd9b-xpnbw
      b: nobody
  size: 1
```

Navigating again to the CRD instance shows the react error.  It seems like the level of nesting is important - it can handle a single level of nested objects, but not a second level of nested objects.

This is a problem for us, as our Helm based operator contains objects which may have arbitrary depth, and we don't necessarily know the names of the nested fields.  It's understandable if the console can't display the information in this field, but it seems better if the console could display the other displayable fields, instead of the React error.

Thanks for your help with this issue!
