### ISSUE TITLE
HELM3 : values.yaml is re-ordered and comments stripped in edit window

### ISSUE THREAD

**Issue by morstad** [openshift/console#4736]
The values.yaml content displayed on install is re-ordered with comments stripped.  Removal of comments and re-ordering is concerning for following reasons  :  
- global and / or common parameters which need to be updated by user aren't displayed at top
- comments to guide users input are removed (thisincludes license acceptance text and pointer to README.MD externally hosted as not displayed during install flow in 4.4)
- parameter order doesn't follow install documentation

Example edit screen : 
![image](https://user-images.githubusercontent.com/24810680/76712960-39207e80-66eb-11ea-8f6c-b0f366c2a20a.png)

Source values.yaml : 
```
# For additional details regarding install parameters see : https://ibm.biz/oms-pro-install

global:
  # Change license to true to indicate have read and agree to license agreement : ibm/biz/oms-license
  licenseAccept: false
  license_store_call_center: true
  image:
    repository: ""
  appSecret: ""
...
```

@sbose78 @siamaksade @pedjak
