### ISSUE TITLE
Populate name of CatalogSource into filter sidebar for custom catalogs

### ISSUE THREAD

**Issue by amobrem** [openshift/console#4752]
When you add a customer CatalogSource, it currently shows up as “Custom” for the provider type instead of using the catalog display name. 

The proposal would be to use the following naming scheme via annotation to display this, and fall back to the actual name of the CatalogSource if not set. As you can see, this means it will need to be truncated in some cases.

```
kind: CatalogSource
apiVersion: v1
metadata:
  name: my-operators-list
  annotations:
    mylist.openshift.io/display-name: “My List"
```

**Folks using custom catalogs today:**
 - groups of packaged software
 - developer workflow with SDK
 - hosting providers that want to curate a catalog

***Design***
[https://github.com/openshift/openshift-origin-design/pull/368](https://github.com/openshift/openshift-origin-design/pull/368)

***Acceptance Criteria:***

- A CatalogSource loaded into the cluster with the correct annotation shows the display name in the Provider Type filter
- A CatalogSource loaded into the cluster without the correct annotation shows the object name in the Provider Type filter, truncated if needed
- Red Hat, Certified and Community hardcoded catalog names remain in place until we can get them to move to this annotation in the future.
