### ISSUE TITLE
OLM text descriptor is being added to all items (select no longer working)

### ISSUE THREAD

**Issue by bfabec** [openshift/console#4885]
With the current version (master branch) of the openshift/console, when trying to create an instance of a csv that contains the `urn:alm:descriptor:com.tectonic.ui:select` specDescriptor, it shows it as a `text` type instead. 

The specDescriptor looks like the following (note, there is no `text` descriptor).
```
      - description: License
        displayName: License
        path: license
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:accept
        - urn:alm:descriptor:com.tectonic.ui:select:not-accept
```

<img width="632" alt="Screen Shot 2020-04-01 at 9 16 51 PM" src="https://user-images.githubusercontent.com/6558437/78204588-80cf3600-745f-11ea-8a30-cdb9c7c1f718.png">

Debugging it further, I put a console log within and saw that my path/capabilties was including an additional descriptor `text` that I did not specify within the csv. It looks like it is adding `text` descriptor to each of specDescriptor.

```
Path: spec.license
Capabilities:  urn:alm:descriptor:com.tectonic.ui:select:accept,urn:alm:descriptor:com.tectonic.ui:select:not-accept,urn:alm:descriptor:com.tectonic.ui:text
```

Because select comes after text within the list of conditions, it is treating spec.license as text even though I want it as select.  My temporarily workaround is to move the select condition above the text condition, but understanding why its appending the `text` descriptor to everything is really what is needed.

https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/create-operand-form.tsx#L885

https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/create-operand-form.tsx#L940
