### ISSUE TITLE
k8sResourcePrefix descriptor with custom resource

### ISSUE THREAD

**Issue by skuffe** [openshift/console#5709]
Hello,

In the operator i am currently developing, i would like to have a dropdown on the creation form of one of my CR's where i can select another CR. I though the k8sResourcePrefix descriptor would do this, but it doesn't seem to work when specifying a custom resource, or perhaps i am specifying it incorrectly?

My descriptor in the CSV is defined like this

```yaml
- description: System owning the application
  displayName: Owner System
  path: system
  x-descriptors:
  - urn:alm:descriptor:io.kubernetes:DCSystem
```

Group, version, kind of my CR
* group: dc-operator.dac.local
* version: v1alpha1
* kind: DCSystem

I have tested out with one of the native kubernetes resources like 'Secret' and that works fine.
If i try with my custom resource, and switch to the form view on the operand creation page, all i get is a blank white page.

OpenShift Version: 4.4.7
OLM: 0.14.2
Kubernetes Version: v1.17.1+f5fb168
