### ISSUE TITLE
Console UI crashes on fieldDependency with same property name

### ISSUE THREAD

**Issue by bfabec** [openshift/console#6182]
With OCP 4.5+, the console UI crashes due to what seems to be the path property name contains the same property name of the fieldDependency. In the following example, `enabled` is in both the path `topology.appDisco.enabled` and the x-descriptor `urn:alm:descriptor:com.tectonic.ui:fieldDependency:topology.enabled:true`:

```
      - description: Enable Application Discovery  and Application Discovery  Observer
        displayName: Application Discovery
        path: topology.appDisco.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:topology.enabled:true
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:topology
```

When trying to create the custom resource via the OCP UI via the Form view, the browser crashes:
```
vendors~main-chunk-7a7a26f2297ed1999af3.min.js:161388 RangeError: Maximum call stack size exceeded
    at Object.t.a (vendors~main-chunk-7a7a26f2297ed1999af3.min.js:18508)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
    at s (create-operand-chunk-b84d6e080d8c4e9c11ea.min.js:1)
```

If I change the property name of the path or fieldDependency to be unique from each other (i.e. enabledx), the UI works. We also didn't see this problem in OCP 4.4, but only within OCP 4.5+.
