### ISSUE TITLE
UI Screen of the Origin console is empty with the web browser

### ISSUE THREAD

**Issue by cmoulliard** [openshift/console#6982]
### Issue

UI Screen of the Origin console is empty with the web browser
I can curl the console and I got this response
```
curl localhost/console
<!DOCTYPE html>
<html lang="en" class="no-js">

  <head>
    <base href="/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>OKD</title>
      <meta name="application-name" content="OKD">
      <link rel="shortcut icon" href="static/assets/okd-favicon.png">
      <link rel="apple-touch-icon-precomposed" sizes="144x144" href="static/assets/okd-apple-touch-icon-precomposed.png">
      <link rel="mask-icon" href="static/assets/okd-mask-icon.svg" color="#DB242F">
      <meta name="msapplication-TileColor" content="#000000">
      <meta name="msapplication-TileImage" content="static/assets/okd-mstile-144x144.png">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript">
      window.SERVER_FLAGS = {"consoleVersion":"v6.0.6-12207-ga37ad18525","authDisabled":true,"kubectlClientID":"","basePath":"/","loginURL":"/auth/login","loginSuccessURL":"/","loginErrorURL":"/error","logoutURL":"/auth/logout","logoutRedirect":"","requestTokenURL":"","kubeAdminLogoutURL":"","kubeAPIServerURL":"https://kubernetes.default","prometheusBaseURL":"","prometheusTenancyBaseURL":"","alertManagerBaseURL":"","meteringBaseURL":"","branding":"okd","customProductName":"","customLogoURL":"","statuspageID":"","documentationBaseURL":"","alertManagerPublicURL":"","grafanaPublicURL":"","prometheusPublicURL":"","thanosPublicURL":"","loadTestFactor":0,"inactivityTimeout":0,"GOARCH":"","GOOS":"","graphqlBaseURL":"/api/graphql"};
    </script>
  <link href="static/170.app-bundle.7df366fcb4d64536d8f7.css" rel="stylesheet"><link href="static/245.app-bundle.59a1441ac5b83dc5094b.css" rel="stylesheet"></head>

  <body class="pf-m-redhat-font">
    <noscript>JavaScript must be enabled.</noscript>
    <div id="popper-container"></div>
    <div id="app"></div>
  <script type="text/javascript" src="static/main-chunk-9ef3b775039306b36987.min.js"></script><script type="text/javascript" src="static/runtime~main-bundle-11336e10578f11f3b406.min.js"></script><script type="text/javascript" src="static/vendors~main-chunk-9ed0d2e9a41627f5da21.min.js"></script></body>
</html>
```

The browser console reports the following errors
```
Active plugins: [@console/app, @console/ceph-storage-plugin, @console/container-security, @console/dev-console, @console/knative-plugin, @console/kubevirt-plugin, @console/local-storage-operator-plugin, @console/metal3-plugin, @console/network-attachment-definition-plugin, @console/noobaa-storage-plugin, @console/operator-lifecycle-manager]
main-chunk-9ef3b775039306b36987.min.js:1 GET http://localhost:9000/api/console/knative-event-sources 502 (Bad Gateway)
main-chunk-9ef3b775039306b36987.min.js:1 GET http://localhost:9000/api/console/knative-channels 502 (Bad Gateway)
main-chunk-9ef3b775039306b36987.min.js:1 GET http://localhost:9000/api/kubernetes/apis/ocs.openshift.io/v1/namespaces/openshift-storage/storageclusters? 502 (Bad Gateway)
main-chunk-9ef3b775039306b36987.min.js:1 GET http://localhost:9000/api/kubernetes/openapi/v2 net::ERR_ABORTED 502 (Bad Gateway)
main-chunk-9ef3b775039306b36987.min.js:1 Could not get OpenAPI definitions Error: Bad Gateway
    at u (main-chunk-9ef3b775039306b36987.min.js:1)
    at main-chunk-9ef3b775039306b36987.min.js:1
main-chunk-9ef3b775039306b36987.min.js:1 GET http://localhost:9000/api/kubernetes/apis/apiregistration.k8s.io/v1/apiservices? net::ERR_ABORTED 502 (Bad Gateway)
main-chunk-9ef3b775039306b36987.min.js:1 Error fetching CRDs for dynamic event sources Error: GET request failed: Get https://127.0.0.1:59041/apis/apiextensions.k8s.io/v1/customresourcedefinitions?labelSelector=duck.knative.dev%2Fsource%3Dtrue: dial tcp 127.0.0.1:59041: connect: connection refused
    at main-chunk-9ef3b775039306b36987.min.js:1
(anonymous) @ main-chunk-9ef3b775039306b36987.min.js:1
i @ main-chunk-9ef3b775039306b36987.min.js:1
Promise.then (async)
l @ main-chunk-9ef3b775039306b36987.min.js:1
main-chunk-9ef3b775039306b36987.min.js:1 GET http://localhost:9000/api/kubernetes/apis net::ERR_ABORTED 502 (Bad Gateway)
(anonymous) @ vendors~main-chunk-9ed0d2e9a41627f5da21.min.js:1
main-chunk-9ef3b775039306b36987.min.js:1 Unhandled promise rejection PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: Error: Bad Gateway
    at u (http://localhost:9000/static/main-chunk-9ef3b775039306b36987.min.js:1:…, type: "unhandledrejection", target: Window, …}
window.onunhandledrejection @ main-chunk-9ef3b775039306b36987.min.js:1
main-chunk-9ef3b775039306b36987.min.js:1 Uncaught (in promise) Error: Bad Gateway
    at u (main-chunk-9ef3b775039306b36987.min.js:1)
    at main-chunk-9ef3b775039306b36987.min.js:1
```

Log of pod reports
```
2020-10-22T18:21:12Z http: proxy error: dial tcp 127.0.0.1:59041: connect: connection refused                                                                    
2020-10-22T18:21:12Z http: proxy error: dial tcp 127.0.0.1:59041: connect: connection refused
```
But I can call from my machine the address
```
curl -k https://127.0.0.1:59041
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1",
    "/apis/admissionregistration.k8s.io/v1beta1",
...
```

### Information

Yaml resources deployed on a kubernetes cluster 1.19
```
kubectl create serviceaccount console -n kube-system
kubectl create clusterrolebinding console --clusterrole=cluster-admin --serviceaccount=kube-system:console -n kube-system

cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-console
  namespace: kube-system
  labels:
    app: origin-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: origin-console
  template:
    metadata:
      labels:
        app: origin-console
    spec:
      containers:
        - name: origin-console-container
          image: quay.io/openshift/origin-console:4.6.0
          env:
            - name: BRIDGE_USER_AUTH
              value: disabled
            - name: BRIDGE_K8S_MODE
              value: off-cluster
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
              value: https://kubernetes.default
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
              value: "true"
            - name: BRIDGE_K8S_AUTH
              value: bearer-token
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: default-token-6v8zb
                  key: token

---
kind: Service
apiVersion: v1
metadata:
  name: origin-console-svc
  namespace: kube-system
spec:
  selector:
    app: origin-console
  ports:
  - name: http
    port: 80
    targetPort: 9000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: origin-console-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /console
        backend:
          serviceName: origin-console-svc
          servicePort: 80
EOF
```

**Comment by cmoulliard** [comment]
I was able to fix the issue after adding the following rbac and deployment change. 

**IMPORTANT**: That should be great to document it like also how to install the kubernetes resources to be used to deploy the okd console

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: console
    namespace: kube-system
```
and of course, we must specify to the deployment, the sa to be used
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: origin-console
  namespace: kube-system
  labels:
    app: origin-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: origin-console
  template:
    metadata:
      labels:
        app: origin-console
    spec:
      serviceAccountName: console
      containers:
        - name: origin-console-container
          image: quay.io/openshift/origin-console:4.6.0
          env:
            - name: BRIDGE_USER_AUTH
              value: disabled
            - name: BRIDGE_K8S_MODE
              value: off-cluster
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
              value: https://kubernetes.default
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
              value: "true"
            - name: BRIDGE_K8S_AUTH
              value: bearer-token
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: default-token-6v8zb <--- TO BE CHANGED
                  key: token
```
