### ISSUE TITLE
specDescriptors and console UI doesn't support object array

### ISSUE THREAD

**Issue by sxd** [openshift/console#7072]
When having this definition on a CRD 

```yaml
parameters:
  additionalProperties:
    type: string
  type: object
```
With the object defined like this:

```go
        Parameters map[string]string `json:"parameters,omitempty"`
```

The console UI can't render the object as it should, or at least, I wasn't able to render this with any of the types I've tried.

Help needed here to understand if this it's a bug or just me that doesn't understand how to render this object
