### ISSUE TITLE
OIDC authentication loop

### ISSUE THREAD

**Issue by kanadaj** [openshift/console#7853]
When installed with the authentication mode set to OIDC via the env variable BRIDGE_USER_AUTH=oidc, the console seems to be looping after authentication to login -> oidc -> callback -> / -> logout.

The console has no errors whatsoever so I assume this might be an issue with how the oidc sessions are stored.

**Comment by kanadaj** [comment]
Okay, it seems this only happens if `BRIDGE_K8S_AUTH` is set to something other than `oidc` - I'm guessing `BRIDGE_K8S_AUTH` shares state with `BRIDGE_USER_AUTH`. Some documentation on this would be welcome!

On that note, it would be great to have some docs w/r to making as much of Bridge work on upstream k8s as possible, like monitoring and maybe even the dashboard (whatever parts are applicable).  It's by far the most functional dashboard for Kubernetes from my experience, with the lack of proper documentation being the only thing weighing it down.

**Comment by stempher** [comment]
You have added the oidc parameters to the api server?

**Comment by kanadaj** [comment]
@stempher I've since then figured this out (it's been 3 months...) but there is a severe lack of documentation around the whole oidc setup so it took some experimentation.

**Comment by Born2Bake** [comment]
> @stempher I've since then figured this out (it's been 3 months...) but there is a severe lack of documentation around the whole oidc setup so it took some experimentation.

Hi, could you please share what ENV vars did you use to configure console with OIDC? I found this but it's not working https://gist.githubusercontent.com/kvaps/f070eff1081bdbc4ee29de4d5555da3d/raw/7f07a39eb7571cd5587ccb9f265533107d65dd8a/openshift-console.yaml

**Comment by kanadaj** [comment]
@Born2Bake 

BRIDGE_K8S_AUTH: oidc
BRIDGE_USER_AUTH: oidc
BRIDGE_USER_AUTH_OIDC_ISSUER_URL: your-issuer-url
BRIDGE_USER_AUTH_OIDC_CLIENT_ID: your-client-id
BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET: your-client-secret

These are all needed, along with setting up the Kubernetes API to use OIDC as per https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens.

Then you need to create a UserRole with the subject name set to the email address (if you set the kubeapi username-claim to email. If it's not email, please consult the above documentation page for --oidc-username-claim and --oidc-username-prefix)

**Comment by abdennour** [comment]
@kanadaj I applied accordingly. but the loop remains.
I can see error of websocket.
Also i can see 401 and 403

i am using keycloak . console redirects to it, but after login, it keep looping.
I added cluster role binding :

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-user-abdennour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: https://keycloak.company.co/auth/realms/myrealm#abdennour
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: abdennour
```
but loop remains
i am not sure this is what you meant by "UserRole " or not.

Regarding websocket issue (wss), i tried the following in ingress
```yaml
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
      }
```
However, wss:// issue still exists. May be it requires change on the corporate LB firewalls/settings
: (
