### ISSUE TITLE
OLM Form View fieldDependency supports only for single parameter.

### ISSUE THREAD

**Issue by lpchitta** [openshift/console#8121]
Currently fieldDependency only works for single parameter which means if we want to display certain configuration only when certain parameter is selected which only works for single parameter but if it allow us to specify multiple parameters then we can control number configurations in UI.

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013

**Comment by TheRealJon** [comment]
@lpchitta I'm not sure which way to interpret this. Are you asking for support for one control field to many dependent fields? Or one dependent field controlled by many control fields?

**One control field controlling many dependent fields (currently supported):**
Dependency is defined on the **dependent field**, so you can easily create multiple dependencies with the same control field. You would just use the same control field path in your fieldDependency descriptor on every dependent field. For example if you have a boolean field with path "showStuff" and you want that field to control the visibility of 3 fields with paths `foo`, `bar.baz`, and `stuff.things.here`, you just need to apply the descriptors like this:

```yaml
specDescriptors:
  - path: foo
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
  - path: bar.baz
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
  - path: stuff.things.here
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
  ```

** One (or more) dependent fields controlled by many control fields (not currently supported)**
If on the other hand you want something like this:
```yaml
specDescriptors:
  - path: foo
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:otherController:true'
  ```
where `foo` would only be visible when `showStuff` and `otherController` are both `true`, we don't currently support that.

For the latter, we would need to open an RFE to get it into our development pipeline.
