### ISSUE TITLE
k8sResourcePrefix descriptor with CRD not displays if owner and reference are in the same Group

### ISSUE THREAD

**Issue by dmvolod** [openshift/console#8296]
We have a situation when one CRD structure links to another CRD structure and both have the same Group name.
For example, we have following `ClusterServiceVersion` fragment with k8sResourcePrefix `x-descriptors`
```
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Backup is the Schema for the backups API
        kind: Backup
        name: backups.infinispan.org
        version: v2alpha1
        displayName: Backup
        specDescriptors:
          - displayName: Cluster name
            description: Infinispan cluster name
            path: cluster
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:org.infinispan:v1:Infinispan'
      - description: Restore is the Schema for the restores API
        kind: Restore
        name: restores.infinispan.org
        version: v2alpha1
        displayName: Restore
        specDescriptors:
          - displayName: Cluster name
            description: Infinispan cluster name
            path: cluster
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:org.infinispan:v1:Infinispan'
          - displayName: Backup name
            description: Infinispan backup object to be restored
            path: backup
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes:org.infinispan:v2alpha1:Backup'
```
But there is not LOV for Infinispan and Backup CR's in the OLM form, i.e.
![image](https://user-images.githubusercontent.com/24249373/109869158-93f31300-7c79-11eb-8ce6-0b280cafee83.png)

If use any CRD outside current Group (infinispan.org) all is working as expected. LOV's are present
