### ISSUE TITLE
Port field disappeared from form view when we add validation rule as ` x-kubernetes-int-or-string: true`

### ISSUE THREAD

**Issue by wuchaof** [openshift/console#8298]
I want to add validation rule for port field in CRD, then we can set the port as a number or a string, but after I adding the validation rule, the port field disappeared from form ui.
crd setting:
```
                                port:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  description: Name or number of the port to access
                                    on the container. Number must be in the range
                                    1 to 65535. Name must be an IANA_SVC_NAME.
                                  x-kubernetes-int-or-string: true
```
