### ISSUE TITLE
Fields dependency not work for those fileds under an array object

### ISSUE THREAD

**Issue by wuchaof** [openshift/console#8299]
I want to set fielddependency for fields under an array object, but it doesn't work. Like below crd, I want to show oracle_url only when `db_type: oracle`. I set dependency on `oracle_url` but doesn't work. dependency only works when `os_datasource` is an object.
```
datasource:
  os_datasource:
    - db_type: oracle/db2
       oracle_url: ***
       db2_stanby_info: ***
  
```
