### ISSUE TITLE
cascading dependencies doesn't work

### ISSUE THREAD

**Issue by wuchaof** [openshift/console#8300]
OCP 4.6
I have a crd section like below, and I set `ssl_enabled` displayed when `deploy_service` as true, and `ssl_secret_name` displayed when `ssl_enabled` as true.  
In Form view, I set  `deploy_service: true` then set `ssl_enabled: true`, at last I see `ssl_secret_name` field
I want to set `deploy_service: **false**`, and expect both  `ssl_enabled` and `ssl_secret_name` disappeared  from UI. But actually `ssl_secret_name` still show there.

```
deploy_service: true
ssl_enabled: true
ssl_secret_name: ***
```

**Comment by wuchaof** [comment]
cc @lpchitta

**Comment by TheRealJon** [comment]
Duplicates https://github.com/openshift/console/issues/8121 tracked by https://issues.redhat.com/browse/RFE-1690

**Comment by wuchaof** [comment]
@TheRealJon I think this one is not the same issue with #8121, 
8121 is required UI to support this descriptors.
```
specDescriptors:
  - path: foo
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:otherController:true'
```
this issue not descriptors related. Like with below CSV. Current descriptors could show foo, foo2 as expected. But when I set `showStuff` as false, I expect `foo2` been hidden together with `foo`, current UI only hide `foo`, `foo2` still show there.
```
specDescriptors:
  - path: foo
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
  - path: foo2
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:foo:true'
```

**Comment by TheRealJon** [comment]
@wuchaof If we supported many-to-one dependencies, you could implement a "cascading" dependency like this:
```yaml
specDescriptors:
  - path: foo
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
  - path: foo2
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:showStuff:true'
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:foo:true'
```
