### ISSUE TITLE
Fields display order in form view not the same as CRD

### ISSUE THREAD

**Issue by wuchaof** [openshift/console#8301]
We defined our fields in crd according to our published cr templated. Customer already familiar with the fields order. So we expect form view also display fields as the same order with we defined in CRD.
But actually form view will display the fields which been depended by other fields in the end of sibling fields.
like in crd we have
```
appversion: 21.0.1
ibm_license: true
new_feature_2101:    // this displayed when `appversion` is 21.0.1
```
in form view, it will show as 
```
ibm_license: true
appversion: 21.0.1
new_feature_2101: 
```

**Comment by wuchaof** [comment]
cc @lpchitta

**Comment by TheRealJon** [comment]
@wuchaof In what version are you seeing this issue? Are you using spec descriptors in your CSV as well? Is your CRD accessible somewhere that I can take a look so I can try to reproduce?

**Comment by TheRealJon** [comment]
cc @tlwu2013

**Comment by wuchaof** [comment]
@TheRealJon  I am using 4.6 OCP. We have spec descriptors in CSV like below.

```
specDescriptors:
  - path: new_feature_2101
     x-descriptors:
       - 'urn:alm:descriptor:com.tectonic.ui:fieldDependency:appversion: 21.0.1'
```
