### ISSUE TITLE
Checkbox showing up as slider

### ISSUE THREAD

**Issue by nschambu** [openshift/console#8323]
**Problem description**

When I attempt to use the `urn:alm:descriptor:com.tectonic.ui:checkbox` x-descriptor in my Operator's CSV, it shows up in the UI as a slider. For example, I have these properties in my CSV:

```yaml
    specDescriptors:
      - displayName: Is Current
        path: "current"
        x-descriptors:
        - "urn:alm:descriptor:com.tectonic.ui:checkbox"
      - displayName: Operand License Structure
        path: license
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - displayName: Accept Operand License
        path: license.accept
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:checkbox'
      - displayName: Key From
        path: license.keyFrom
      - displayName: Secret Key Ref
        path: license.keyFrom.secretKeyRef
      - displayName: Operand License Key
        path: license.keyFrom.secretKeyRef.name
        x-descriptors:
        - 'urn:alm:descriptor:io.kubernetes:Secret'
```

This displays as the following:

![Screen Shot 2021-03-05 at 1 57 16 PM](https://user-images.githubusercontent.com/45972912/110334143-0c463500-7fe8-11eb-972f-042186f0605f.png)

**Expected Result**

I expected the checkbox properties to show up as checkboxes, like the [example here](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#5-checkbox)

**Environments**

I tested this on OCP 4.5 and 4.6
