### ISSUE TITLE
[4.8] KubeVirt Plugin not working because OpenShift Virtualization installs CRDs with v1alpha3

### ISSUE THREAD

**Issue by jomeier** [openshift/console#9227]
Hi,

in OKD 4.8 nightlies we miss the side menu "Workloads -> Virtualization" in the Web Console if OpenShift Virtualization is installed. I think there is a problem with the Web Console.

This properly works with OKD 4.7 but seems to be a problem with latest 4.8 nightlies.

So I assume it's also a problem in OpenShift 4.8.

https://bugzilla.redhat.com/show_bug.cgi?id=1971188

Greetings,

Josef

**Comment by jomeier** [comment]
An answer in https://bugzilla.redhat.com/show_bug.cgi?id=1971188 says that a few weeks ago a change was introduced that the web console only shows CRDs with version v1:

https://github.com/openshift/console/commit/8c55c7a157117c292628163141bca1b8dfd4ba90

Introduced the problem.

OpenShift Virtualization from the Red Hat Operatorhub catalog (Version 2.6.5, current version) still installs CRDs with v1alpha3. KubeVirt resources like VirtualMachine won't be shown in the Web Console.

Could you revert that, please @yaacov 

Thanks and greetings,

Josef

**Comment by yaacov** [comment]
@jomeier thanks for the issue

**Comment by spadgett** [comment]
@yaacov Is this addressed by #9326 or is there still an issue?

**Comment by yaacov** [comment]
> @yaacov Is this addressed by #9326 or is there still an issue?

Bug is verified as fixed on 4.8
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1971188

cc:// @gouyang

**Comment by spadgett** [comment]
> Bug is verified as fixed on 4.8
> BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1971188

Closing the issue as this is fixed.

**Comment by davidpanic** [comment]
Correct me if I'm wrong, but this seems to have regressed in 4.10. I am able to see the `Virtualization` tab if I use the image `quay.io/openshift/origin-console:4.9` but not if I use `quay.io/openshift/origin-console:4.10`.

<details>
<summary>Used manifest (click to expand)</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  namespace: openshift-console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - env:
            - name: BRIDGE_K8S_AUTH
              value: bearer-token
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              [redacted]
            - name: BRIDGE_K8S_MODE
              value: off-cluster
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
              value: https://kubernetes.default.svc
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
              value: "true"
            - name: BRIDGE_USER_AUTH
              value: disabled
          image: quay.io/openshift/origin-console:4.10
          name: console
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
```
</details>

## Screenshots

**4.9**:
![image](https://user-images.githubusercontent.com/13370323/221217109-3caf229b-170a-4f3c-a2e2-cde96c753a58.png)

**4.10**:

![image](https://user-images.githubusercontent.com/13370323/221217423-799fb6fa-6ef2-40fe-9695-f8ebd2c7bb55.png)
