### ISSUE TITLE
Native Kubernetes Deployment + Keycloak as OIDC instead of DEX - avoid looping

### ISSUE THREAD

**Issue by abdennour** [openshift/console#9754]
I tried to deploy the OKD origin-console using [this helm chart](https://artifacthub.io/packages/helm/av1o-charts/openshift-console). & using keycloak realm instead of DEX , on top of a native kubernetes v1.19.13

After installing the chart, my deployment looks like: 
```yaml
      - env:
        - name: BRIDGE_DOCUMENTATION_BASE_URL
          value: https://kubernetes.io/docs/
        - name: BRIDGE_DEX_API_HOST
          value: https://keycloak.example.co/auth/realms/realm-x
        - name: BRIDGE_BASE_ADDRESS
          value: https://console.devops.example.co
        - name: BRIDGE_USER_AUTH
          value: oidc
        - name: BRIDGE_K8S_AUTH
          value: oidc
        - name: BRIDGE_USER_AUTH_OIDC_ISSUER_URL
          value: https://keycloak.example.co/auth/realms/realm-x
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_ID
          value: console
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET
          value: yyyyyyy-xxxx-zzzz-tttt-xxxxxxxxxx
        image: quay.io/openshift/origin-console:4.6.0
```

The console is able to redirect me to the keycloak login page. However, after a success login, i cannot see everything in the console. I just see infinite loop of  page refresh.

These are my questions :
- Is it possible to integrate correctly with Keycloak as OIDC provider instead of Dex ?
- What are the missing env vars ? because after some research, i found [someone](https://www.reddit.com/r/kubernetes/comments/d50oe9/openshift_web_ui_on_upstream_k8s/f0jg8tl/) to refer to other env vars like : `BRIDGE_KUBECTL_CLIENT_ID`, `BRIDGE_KUBECTL_CLIENT_SECRET` which i don't know how to assign a value for them ?
- What are the required clusterrolebinding ?
- For the websocket, what's the required annotations at ingress level, so i can avoid failed websocket ?
- What are the CRDs that i must deploy to the native kubernetes ? so i can take the most benefit from the console . For example, the helm chart mentioned at the beginning deploys the CRD "app" of Openshift.

Note that [this configuration](https://github.com/openshift/console/issues/1377#issuecomment-604146607) is working with me. However, it does not delegate to users with RBAC.
